Remove reset_gop_hash and update_gop_hash APIs
AxisCommunications/signed-video-framework pull request #265
Opened 2024-12-05 14:12 UTC by mithydolphin

These APIs are no longer needed as recursive hash is not used.

### Describe your changes

Please include a summary of the change, a relevant motivation and context.

### Issue ticket number and link

- Fixes #(issue)

### Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have verified that the code builds perfectly fine on my local system
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have verified that my code follows the style already available in the repository
- [ ] I have made corresponding changes to the documentation

2024-12-05 15:20 UTC, lusikamalo commented on lib/src/signed_video_h26x_auth.c
> +#include "signed_video_h26x_internal.h"  // gop_state_*() , update_validation_flags()
nit: remove space.

2024-12-05 15:21 UTC, lusikamalo commented on lib/src/signed_video_h26x_sign.c
> +    self->gop_info->num_nalus_in_gop_hash = 0;
You already got "gop_info" from row 350.

2024-12-05 15:23 UTC, lusikamalo requested changes
Just some minor stuff.

2024-12-05 15:40 UTC, bjornvolcker approved these changes

2024-12-05 15:42 UTC, bjornvolcker approved these changes

2024-12-05 15:42 UTC, bjornvolcker commented on lib/src/signed_video_h26x_common.c
> -  return openssl_hash_data(self->crypto_handle, &gop_info->gop_hash_init, 1, gop_info->gop_hash);
We should write a ticket to init the new gop hash computation with gop_hash_init.

2024-12-06 07:58 UTC, lusikamalo approved these changes
OK.

2024-12-06 14:03 UTC, merged