Adds payload_buffer and last_two_bytes_buffer to struct
AxisCommunications/signed-video-framework pull request #94
Opened 2022-08-05 12:03 UTC by Caroline-Holmstrom

2022-08-05 12:23 UTC, bjornvolcker requested changes

2022-08-05 12:23 UTC, bjornvolcker commented on lib/src/signed_video_internal.h
>    uint16_t last_two_bytes_buffer[MAX_NALUS_TO_PREPEND];
Remove this buffer.

2022-08-05 12:23 UTC, bjornvolcker commented on lib/src/signed_video_internal.h
>    // Buffer of payload pointer pairs. Each pair holds the memory for a SEI in preparation and to be
Move and adjust these descriptions to the new `sei_data_t` struct

2022-08-05 12:23 UTC, bjornvolcker commented on lib/src/signed_video_internal.h
> +  int sei_data_buffer_idx;
Put these where the other buffers were located.

2022-08-05 12:23 UTC, bjornvolcker commented on lib/src/signed_video_h26x_sign.c
>  /* Frees all payloads in the |payload_buffer|. Declared in signed_video_internal.h */
Update description

2022-08-05 12:23 UTC, bjornvolcker commented on lib/src/signed_video_h26x_sign.c
>      // memory.
This comment is no longer correct.

2022-08-05 12:23 UTC, bjornvolcker commented on lib/src/signed_video_h26x_sign.c
>  complete_sei_nalu_and_add_to_prepend(signed_video_t *self)
Update description above

2022-08-05 12:23 UTC, bjornvolcker commented on lib/src/signed_video_h26x_sign.c
>    // Done with the SEI payload. Move |payload_buffer|. This should be done even if we caught a
Update comment

2022-08-05 12:23 UTC, bjornvolcker commented on lib/src/signed_video_h26x_sign.c
>    self->last_two_bytes = self->last_two_bytes_buffer[0];
You should use the `sei_data_buffer`. Not the `last_two_bytes_buffer`.

2022-08-08 05:37 UTC, bjornvolcker requested changes

2022-08-08 05:37 UTC, bjornvolcker commented on lib/src/signed_video_h26x_common.c
>      }
You can remove initializing the buffer since we do not take values from it when starting writing the SEI.

2022-08-08 05:37 UTC, bjornvolcker commented on lib/src/signed_video_h26x_sign.c
> +/* Frees all payloads in the |free_sei_data_buffer|. Declared in signed_video_internal.h */
`free_sei_data_buffer` -> `sei_data_buffer`

2022-08-08 05:37 UTC, bjornvolcker commented on lib/src/signed_video_h26x_sign.c
> + * and the last two bytes. If we have no signature the SEI payload is freed and not added to the
Change "and the last two bytes." to "and the stop byte."

2022-08-08 05:37 UTC, bjornvolcker commented on lib/src/signed_video_h26x_sign.c
> +  if (self->sei_data_buffer_idx < 0) return SVI_NOT_SUPPORTED;
Shouldn't this be `< 1`?

2022-08-08 05:37 UTC, bjornvolcker commented on lib/src/signed_video_internal.h
> +  // about to be added.
Move this description up to the definition of the `struct _sei_data_t`

2022-08-08 09:06 UTC, bjornvolcker requested changes

2022-08-08 09:06 UTC, bjornvolcker commented on lib/src/signed_video_internal.h
> +// about to be added.
Not here. Down where the struct is defined.

2022-08-08 09:06 UTC, bjornvolcker commented on lib/src/signed_video_internal.h
> +// Buffer of stop bytes and payload pointer pairs. Writing of the SEI is split in time and it
Change "stop bytes" to "last two bytes"

2022-08-08 10:19 UTC, bjornvolcker approved these changes
LGTM

2022-08-08 11:35 UTC, lusikamalo approved these changes
OK.

2022-08-08 11:36 UTC, merged